### ISSUE TITLE
Bulk Edit function trying to call a non existing method on 'Group' and inconv_set_encoding() error

### ISSUE THREAD

**Issue by mrsteveheyes** [colymba/GridFieldBulkEditingTools#102]
I am using your module and unLink and delete are working great. However, I'm trying to use the Bulk Edit functionality and it's not working. 

When I select a number of dataobjects (these are Members if that helps) to edit, and click the 'Go' button I get two types of errors.

The first is: "[Deprecated] iconv_set_encoding(): Use of iconv.internal_encoding is deprecated" I get 30 of these. 
![screen shot 2015-03-12 at 15 34 49](https://cloud.githubusercontent.com/assets/95527/6621233/5a25a7de-c8cd-11e4-99ed-b7550c0554ac.png)

And then at the bottom I get: "[User Error] Uncaught Exception: Object->__call(): the method 'record_6_permissions' does not exist on 'Group'''
![screen shot 2015-03-12 at 15 34 40](https://cloud.githubusercontent.com/assets/95527/6621238/6180ee8a-c8cd-11e4-9fc6-f4f0cefebfec.png)

I accept that these may not have anything to do with this module but it's only when i use the bulkEdit does it not work. 

I am using CMS 3.1.3 and Framework 3.1.3

Do you want/need any more info?

**Comment by colymba** [comment]
Hi, I don't think the `iconv_set_encoding ` is related, might be a general PHP deprecation?

For the other one, that's tricky. Are you using the latest version? Sounds related to https://github.com/colymba/GridFieldBulkEditingTools/issues/76 but a PR fixed it here https://github.com/colymba/GridFieldBulkEditingTools/commit/1ceee593609c421f1507438304775774ba166251.

Basically it comes from the fact that by editing multiple records in one form we have to rename each field since names have to be unique. Which brings some work arounds to handle Model requests etc. If you are using the latest version, then this will have to be investigated further...

**Comment by robbieaverill** [comment]
Agreed, this sounds like a server (or local) configuration issue
