### ISSUE TITLE
[Warning] include_once(phing/Task.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by botzkobg** [colymba/GridFieldBulkEditingTools#116]
I receive this error with after installing the module with composer. My temporary fix is:
```
if (is_file("phing/Task.php")) 
	include_once "phing/Task.php";
```
but this will be better solution, because it will check also in include_path as include do
```
if (stream_resolve_include_path('phing/Task.php') !== false)
	include_once 'phing/Task.php';
```

Kind regards.

**Comment by colymba** [comment]
The warning is actually expected (was previously an error), see https://github.com/colymba/GridFieldBulkEditingTools/commit/8af962a65dc34ef2bf2fb7b9eccb3a3652dd73f5

Although this is probably not ideal since this Task is only really needed during development of the module. The warning should disappear on a live site though. Maybe there is a better solution....

**Comment by colymba** [comment]
this should be solved by https://github.com/colymba/GridFieldBulkEditingTools/commit/df71f1ffbf3ec15b104e4edaee15be11cdfe9557

feel free to reopen if not solved.
