### ISSUE TITLE
GridFieldBulkUpload attach from files folder selection

### ISSUE THREAD

**Issue by mrbookt** [colymba/GridFieldBulkEditingTools#124]
When I try to bulk upload files from exiting folder I get the popup but once I click on folder dropdown to select files from a different location I receive a 404 error with response:

"I can't handle sub-URLs on class Form."

CMS & Framework 3.3.1 GridFieldBulkEditingTools dev-master

**Comment by colymba** [comment]
Are you using the latest master branch? This commit 22307f6b8f8511a822ee1a5fb020cdf333f2ee2b should have fixed this but hasn't made it into a tagged release yet.

**Comment by mrbookt** [comment]
Yep, I'am using the latest branch and I have changes from this commit. When I click the attach from files button I have files from every folder listed and folder dropdown is empty (choose or search). Pagination on this list throws 404 error as well.

**Comment by bueckl** [comment]
Same thing happening here. @mrbookt did you solve that?

**Comment by colymba** [comment]
I thought this was fixed by https://github.com/colymba/GridFieldBulkEditingTools/commit/22307f6b8f8511a822ee1a5fb020cdf333f2ee2b but that patch doesn't actually change anything, probably should be reverted.

The error basically comes from the requests not being routed properly through the gridfield and to the uploadfield.

Just needs a bit if work :/

**Comment by colymba** [comment]
This should be fixed in master now with 29482dbd17e42c3de364aa3d46d20ba65175c9d3

**Comment by bueckl** [comment]
Yay, works like a charme. Thank You!
