### ISSUE TITLE
404 when using GridFieldBulkUpload

### ISSUE THREAD

**Issue by andreaslindahl** [colymba/GridFieldBulkEditingTools#128]
I'm getting a 404 Not found when using the GridFieldBulkUpload in a GridField:

The browser tries to load the URL http://rtv.dev/admin/pages/edit/EditForm/field/PressImages/bulkupload/folderid which returns "Action 'folderid' isn't available on class GridFieldBulkUpload_Request."

**Comment by mrbookt** [comment]
I'am getting the same error with kickassets module instaled

**Comment by colymba** [comment]
Any idea which front-end action/button triggers the error? I can't find a folderid() method on UploadField.... are you using any other component?

**Comment by mrbookt** [comment]
Yes, kickassets module https://github.com/unclecheese/silverstripe-kickassets. This problem occurs only while this module is installed. Error is triggered when cms page with gridfield bulkupload is loaded. When you click "from files" kickassets modal will open with error as well because there is no folderid defined (folderid method is from kickassets module). There is similar unresolved issue in kickassets module:

https://github.com/unclecheese/silverstripe-kickassets/issues/39

**Comment by colymba** [comment]
Right, this is not really related to this module then. Best at this stage is to have a compatibility layer since it doesn't make sense to add fixes for other modules in here.

And it seems this module solves it: https://github.com/guru-digital/SilverStripe-KickAssets-GridFieldBulkEditing
