### ISSUE TITLE
SS4: Missing "Finish" button after BulkUploader

### ISSUE THREAD

**Issue by axllent** [colymba/GridFieldBulkEditingTools#149]
SilverStripe4-beta2 / GridFieldBulkEditingTools (master): After successfully uploading one or more files via the BulkUploader there is no way to "complete" and reload the gridfield without saving the page or refreshing. The SilverStripe 3 version used to have a "Finish" button which would do that.

**Comment by colymba** [comment]
Right now all the BulkUploader button have been removed.
Since the upload field is a react component, the old entwine code of tracking uploads and errors etc, just doesn't work anymore. So all buttons have been removed.

Removing the finish button, like you pointed out, forces user to use the page's save/publish buttons, which might not be a bad things with SS4 being all Versioned. So `owned` images get published automatically.

I'll be close this, since for now it is a "design/ux choice" not to have anymore buttons.
