### ISSUE TITLE
"Ajax requests to this URL require an X-Pjax header."

### ISSUE THREAD

**Issue by robbieaverill** [colymba/GridFieldBulkEditingTools#157]
When using this module in the SilverStripe comments module, loading the Comments ModelAdmin performs an AJAX request via this module to do something, which fails with the following error message:

```
Ajax requests to this URL require an X-Pjax header.
```

**Comment by colymba** [comment]
Is the issue appearing when the ModelAdmin is loaded? Or after a bulkAction is performed?

I would image after the bulkAction, otherwise this would be link to GridField?...  If it's related to the bulkAction, would adding the headers on the the Handler help (https://github.com/silverstripe/silverstripe-comments/blob/master/src/Admin/CommentsGridFieldBulkAction/Handler.php)? Like here https://github.com/silverstripe/silverstripe-comments/blob/master/src/Admin/CommentsGridFieldBulkAction/Handler.php#L45 ?

**Comment by robbieaverill** [comment]
Thanks for the reply! Yes this happens when you load the ModelAdmin. I'll investigate some more tomorrow. Thanks for the references!

**Comment by colymba** [comment]
right, so that makes it a bit trickier to figure out... since all this does is provide the gridfield with and html fragment...

**Comment by robbieaverill** [comment]
I think this is in fact a comments implementation issue. Thanks for replying, I'll fix this in the module itself.
