### ISSUE TITLE
SS4 stabilisation - placeholder

### ISSUE THREAD

**Issue by robbieaverill** [colymba/GridFieldBulkEditingTools#160]
Hey @colymba!

This issue is hopefully to act more as a placeholder for discussion around when we can stabilise this module for SS4.

We'll be aiming to release CWP 2.0 with SilverStripe 4 around the 1st of March, so we'd need a stable tag by then.

The part of CWP that uses this module is the comments module admin area, and the functionality there in regards to this module is working correctly. I realise there are other parts of this module than that though, so we'd need to factor that in before a stable tag.

Also I've noticed there's a couple of UX issues that've been raised already, e.g. #158, #152, #153 

What do you think about all of this?

**Comment by colymba** [comment]
Hey @robbieaverill, I've actually started on a new version over the new year, which would eventually become 3.0. The branch here is a lot behind what I have locally though (so I would not use it).

The idea is to bring this module to a good SS4 compatibility, like first have it change to a vendor module and restructuring all the folders etc.

Then there are also a few improvements that will make it into the release, like #109 and #153 with Versioned compatibility (since it's an integral part of SS4).

I am short on time as always, but I hope I can get something out during February.

Feel free to list issues and improvements that you would want to see in v3.0 which would help prioritise.

**Comment by mlewis-everley** [comment]
Hi All, I have just created a quick pull request for (what appears to be) correct CSS/JS support for a vendor module.

The current 3.0 branch seems to cause issues (either the location of bulk editing tools seems to be incorrect or vendor folder is blocked by .htaccess).

Hopefully this is a start to stabilisation? Please let me know what you think?

**Comment by colymba** [comment]
A quick note on the progress, am working to bring this module to a stable SS4 compatibility in the 3.0 branch... sorry for the delay in pushing all the updates.

Keep an eye there and let me know of bug/enhancements you can find... thanks!

**Comment by colymba** [comment]
In the latest https://github.com/colymba/GridFieldBulkEditingTools/tree/3.0 all seem to work with SS4. #109 has also just been handled.

I need to tackle the bulk upload and a LOT of cosmetic fixes and clean up... but it's coming along...

**Comment by robbieaverill** [comment]
Awesome :) can we get a beta tag at least? We need this for CWP 2.0

**Comment by colymba** [comment]
Alright just create https://github.com/colymba/GridFieldBulkEditingTools/tree/3.0.0-beta1 the basics should work... but it looks rough on the UI/UX perspective...

**Comment by robbieaverill** [comment]
Ok, thanks :)

**Comment by robbieaverill** [comment]
Going to close this for now, we can log new issues if needed =) Thanks!
